apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: echodoc-voice-agent
    newName: echodoc-voice-agent
    newTag: latest
